client_config_backend: file
client_config:
  client_id: 999460651443-eavmidkbjhrtl7k6rsn0osifq60e8f3n.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.install
